### ISSUE TITLE
error when train on custom dataset

### ISSUE THREAD

**Issue by TahereSaidi** [GiovanniPasq/DA-Faster-RCNN#5] opened 2023-08-02 13:25 UTC
hello again
I want to run it on my own data set and after putting the data set in my drive and addressing it correctly, it gives the following error code:"
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.10/dist-packages/detectron2/data/common.py", line 296, in __iter__
    yield self.dataset[idx]
  File "/usr/local/lib/python3.10/dist-packages/detectron2/data/common.py", line 125, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.10/dist-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/data/dataset_mapper.py", line 154, in __call__
    image = utils.read_image(dataset_dict["file_name"], format=self.image_format)
  File "/usr/local/lib/python3.10/dist-packages/detectron2/data/detection_utils.py", line 180, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "/usr/local/lib/python3.10/dist-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/students_ship_train_images/DCS_115_evening_rainy_180.jpg'" 
by running this line:"do_train(cfg_source,cfg_target,model)" I downloaded rcnn.py and roi.head files from your Github and deleted that files in the mentioned address and uploaded a downloaded file. I did the same for the rest of the steps.
I also registered the dataset correctly:"#This block is an example of how you should use this API
register_coco_instances("dataset1_train_synthetic", {}, "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/Train_in_coco_format.json", "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/students_ship_train_images")
register_coco_instances("dataset1_train_real", {}, "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/_annotations.coco.json", "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/train_target_coco")

register_coco_instances("dataset1_test_real", {}, "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/test_coco_format.json", "/content/drive/MyDrive/PRJ/students_prj_ship_train_val_test_dataset/students_ship_test_dataset")"
Why does it give this error?

**Comment by GiovanniPasq** [comment] 2023-08-02 16:50
Hello, can you try to replace from the paths "/content/drive/MyDrive/" with "drive/My Drive/"?

**Comment by TahereSaidi** [comment] 2023-08-02 17:24
i do this and the error is:"
FileNotFoundError: [Errno 2] No such file or directory: '/drive/MyDrive/labels/Train_in_coco_format.json'"

**Comment by GiovanniPasq** [comment] 2023-08-02 17:28
"My Drive" not "MyDrive" add the space

**Comment by TahereSaidi** [comment] 2023-08-02 17:29
I found that there was a bug in my labels that when converting from pascal to cocoa an extra DC suffix was added to it. I fixed this but now the error it gives is that it cannot access the image files

**Comment by GiovanniPasq** [comment] 2023-08-02 17:34
it is hard to fix the problem if it is related to your paths or labels. I can say that you can also use the repo with Pascal voc annotations using the API register_pascal_voc as i reported in the read me to prevent error when you convert them from Pascal voc to COCO

**Comment by TahereSaidi** [comment] 2023-08-02 17:35
still error is: FileNotFoundError: [Errno 2] No such file or directory: '/drive/My Drive/labels/Train_in_coco_format.json'
The problem is that the dataset is large and I don't know how many clas

**Comment by GiovanniPasq** [comment] 2023-08-02 17:46
Nope, the problem is that the file is not found. Are you sure you imported the file in your drive? Did you use 
```
from google.colab import drive
drive.mount('/content/drive')
```
before loading the dataset with the coco api?

**Comment by TahereSaidi** [comment] 2023-08-02 18:53
yes i imported and use drive .mount

**Comment by GiovanniPasq** [comment] 2023-08-02 19:59
Ok if you checked that the path are correct i think the problem is related to the dataloader with google colab when the dataset is large.
Please try the following two step in order a few times (maybe 10/15):
1. Restart the run time of the google colab
2. Run all the blocks (it is not necessary to run the block that contains the detectron2 installation)

If this does not work, please read this, i found a similar problem on stackoverflow:

https://stackoverflow.com/questions/65568015/filenotfound-error-while-reading-images-from-gdrive-in-colab

**Comment by TahereSaidi** [comment] 2023-08-03 13:48
i solve my problem 
after "Register your Dataset" before cell of coco format i use this:"%cd /content"
and then:
"#This block is an example of how you should use this API
register_coco_instances("dataset_train_synthetic", {}, "drive/MyDrive/Labels/train.json", "./drive/MyDrive/prj/students_prj_ship_train_val_test_dataset/students_ship_train_images")
register_coco_instances("dataset_train_real", {}, "drive/MyDrive/Labels/val.json", "./drive/MyDrive/prj/students_prj_ship_train_val_test_dataset/students_ship_val_images")

register_coco_instances("dataset_test_real", {}, "drive/MyDrive/Labels/test.json", "./drive/MyDrive/prj/students_prj_ship_train_val_test_dataset/students_ship_test_dataset")"
pleace close the issue and thank you.

**Comment by GiovanniPasq** [comment] 2023-08-03 14:33
i am happy to read this message, i am closing the issue :D

**Closed as completed by GiovanniPasq** 2023-08-03 14:33 UTC
